name: cholera-demo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy=1.11.*
  - scikit-learn=1.4.*
  - matplotlib
  - seaborn
  - streamlit
  - jupyter
  - ipywidgets
  - pip
